service: lucidact-test
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-2
  stackName: lucidact-test
  
custom:
  documentation:
    version: '1'
    title: 'My API'
    description: 'This is my API'
    models: {}

layers:
  CommonUtils:
    path: node_modules/lucid-health

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    layers:
      - {Ref: CommonUtilsLambdaLayer}
    events:
      - http:
          path: lucidactTest/generateRandomNumber
          method: get

#Plugins
plugins:
  - serverless-plugin-typescript
  - serverless-openapi-documentation
