service: lucidact-test
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-2

functions:
  hello:
    handler: src/handler.generateRandomNumber
    events:
      - https:
          path: lucidactTest/generateRandomNumber
          method: get

#Plugins
plugins:
  - serveless-plugin-typescript