service: lucidact-test
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-2

functions:
  src/generaterandomnumber:
    handler: src/handler.generateRandomNumber
    events:
      - http:
          path: lucidactTest/generateRandomNumber
          method: get

#Plugins
plugins:
  - serverless-plugin-typescript