
export enum AddressType {
    Home,
    CareCenter,
    Mail,
    Payor,
    Work,
    Other,
    Unknown
}

export enum Country {
    UnitedStates = 'US',
    Afghanistan = 'AF',
    AlandIslands = 'AX',
    Albania = 'AL',
    Algeria = 'DZ',
    AmericanSamoa = 'AS',
    Andorra = 'AD',
    Angola = 'AO',
    Anguilla = 'AI',
    Antarctica = 'AQ',
    AntiguaAndBarbuda = 'AG',
    Argentina = 'AR',
    Armenia = 'AM',
    Aruba = 'AW',
    Australia = 'AU',
    Austria = 'AT',
    Azerbaijan = 'AZ',
    Bahamas = 'BS',
    Bahrain = 'BH',
    Bangladesh = 'BD',
    Barbados = 'BB',
    Belarus = 'BY',
    Belgium = 'BE',
    Belize = 'BZ',
    Benin = 'BJ',
    Bermuda = 'BM',
    Bhutan = 'BT',
    Bolivia = 'BO',
    BonaireSintEustatiusSaba = 'BQ',
    BosniaAndHerzegovina = 'BA',
    Botswana = 'BW',
    BouvetIsland = 'BV',
    Brazil = 'BR',
    BritishIndianOceanTerritory = 'IO',
    BruneiDarussalam = 'BN',
    Bulgaria = 'BG',
    BurkinaFaso = 'BF',
    Burundi = 'BI',
    Cambodia = 'KH',
    Cameroon = 'CM',
    Canada = 'CA',
    CapeVerde = 'CV',
    CaymanIslands = 'KY',
    CentralAfricanRepublic = 'CF',
    Chad = 'TD',
    Chile = 'CL',
    China = 'CN',
    ChristmasIsland = 'CX',
    CocosKeelingIslands = 'CC',
    Colombia = 'CO',
    Comoros = 'KM',
    Congo = 'CG',
    CongoDemocraticRepublic = 'CD',
    CookIslands = 'CK',
    CostaRica = 'CR',
    CoteDIvoire = 'CI',
    Croatia = 'HR',
    Cuba = 'CU',
    Curaçao = 'CW',
    Cyprus = 'CY',
    CzechRepublic = 'CZ',
    Denmark = 'DK',
    Djibouti = 'DJ',
    Dominica = 'DM',
    DominicanRepublic = 'DO',
    Ecuador = 'EC',
    Egypt = 'EG',
    ElSalvador = 'SV',
    EquatorialGuinea = 'GQ',
    Eritrea = 'ER',
    Estonia = 'EE',
    Ethiopia = 'ET',
    FalklandIslands = 'FK',
    FaroeIslands = 'FO',
    Fiji = 'FJ',
    Finland = 'FI',
    France = 'FR',
    FrenchGuiana = 'GF',
    FrenchPolynesia = 'PF',
    FrenchSouthernTerritories = 'TF',
    Gabon = 'GA',
    Gambia = 'GM',
    Georgia = 'GE',
    Germany = 'DE',
    Ghana = 'GH',
    Gibraltar = 'GI',
    Greece = 'GR',
    Greenland = 'GL',
    Grenada = 'GD',
    Guadeloupe = 'GP',
    Guam = 'GU',
    Guatemala = 'GT',
    Guernsey = 'GG',
    Guinea = 'GN',
    GuineaBissau = 'GW',
    Guyana = 'GY',
    Haiti = 'HT',
    HeardIslandMcdonaldIslands = 'HM',
    HolySeeVaticanCityState = 'VA',
    Honduras = 'HN',
    HongKong = 'HK',
    Hungary = 'HU',
    Iceland = 'IS',
    India = 'IN',
    Indonesia = 'ID',
    Iran = 'IR',
    Iraq = 'IQ',
    Ireland = 'IE',
    IsleOfMan = 'IM',
    Israel = 'IL',
    Italy = 'IT',
    Jamaica = 'JM',
    Japan = 'JP',
    Jersey = 'JE',
    Jordan = 'JO',
    Kazakhstan = 'KZ',
    Kenya = 'KE',
    Kiribati = 'KI',
    Korea = 'KR',
    KoreaDemocraticPeoplesRepublic = 'KP',
    Kuwait = 'KW',
    Kyrgyzstan = 'KG',
    LaoPeoplesDemocraticRepublic = 'LA',
    Latvia = 'LV',
    Lebanon = 'LB',
    Lesotho = 'LS',
    Liberia = 'LR',
    LibyanArabJamahiriya = 'LY',
    Liechtenstein = 'LI',
    Lithuania = 'LT',
    Luxembourg = 'LU',
    Macao = 'MO',
    Macedonia = 'MK',
    Madagascar = 'MG',
    Malawi = 'MW',
    Malaysia = 'MY',
    Maldives = 'MV',
    Mali = 'ML',
    Malta = 'MT',
    MarshallIslands = 'MH',
    Martinique = 'MQ',
    Mauritania = 'MR',
    Mauritius = 'MU',
    Mayotte = 'YT',
    Mexico = 'MX',
    Micronesia = 'FM',
    Moldova = 'MD',
    Monaco = 'MC',
    Mongolia = 'MN',
    Montenegro = 'ME',
    Montserrat = 'MS',
    Morocco = 'MA',
    Mozambique = 'MZ',
    Myanmar = 'MM',
    Namibia = 'NA',
    Nauru = 'NR',
    Nepal = 'NP',
    Netherlands = 'NL',
    NewCaledonia = 'NC',
    NewZealand = 'NZ',
    Nicaragua = 'NI',
    Niger = 'NE',
    Nigeria = 'NG',
    Niue = 'NU',
    NorfolkIsland = 'NF',
    NorthernMarianaIslands = 'MP',
    Norway = 'NO',
    Oman = 'OM',
    Pakistan = 'PK',
    Palau = 'PW',
    PalestinianTerritory = 'PS',
    Panama = 'PA',
    PapuaNewGuinea = 'PG',
    Paraguay = 'PY',
    Peru = 'PE',
    Philippines = 'PH',
    Pitcairn = 'PN',
    Poland = 'PL',
    Portugal = 'PT',
    PuertoRico = 'PR',
    Qatar = 'QA',
    Reunion = 'RE',
    Romania = 'RO',
    RussianFederation = 'RU',
    Rwanda = 'RW',
    SaintBarthelemy = 'BL',
    SaintHelena = 'SH',
    SaintKittsAndNevis = 'KN',
    SaintLucia = 'LC',
    SaintMartin = 'MF',
    SaintPierreAndMiquelon = 'PM',
    SaintVincentAndGrenadines = 'VC',
    Samoa = 'WS',
    SanMarino = 'SM',
    SaoTomeAndPrincipe = 'ST',
    SaudiArabia = 'SA',
    Senegal = 'SN',
    Serbia = 'RS',
    Seychelles = 'SC',
    SierraLeone = 'SL',
    Singapore = 'SG',
    SintMaarten = 'SX',
    Slovakia = 'SK',
    Slovenia = 'SI',
    SolomonIslands = 'SB',
    Somalia = 'SO',
    SouthAfrica = 'ZA',
    SouthGeorgiaAndSandwichIsl = 'GS',
    SouthSudan = 'SS',
    Spain = 'ES',
    SriLanka = 'LK',
    Sudan = 'SD',
    Suriname = 'SR',
    SvalbardAndJanMayen = 'SJ',
    Swaziland = 'SZ',
    Sweden = 'SE',
    Switzerland = 'CH',
    SyrianArabRepublic = 'SY',
    Taiwan = 'TW',
    Tajikistan = 'TJ',
    Tanzania = 'TZ',
    Thailand = 'TH',
    TimorLeste = 'TL',
    Togo = 'TG',
    Tokelau = 'TK',
    Tonga = 'TO',
    TrinidadAndTobago = 'TT',
    Tunisia = 'TN',
    Turkey = 'TR',
    Turkmenistan = 'TM',
    TurksAndCaicosIslands = 'TC',
    Tuvalu = 'TV',
    Uganda = 'UG',
    Ukraine = 'UA',
    UnitedArabEmirates = 'AE',
    UnitedKingdom = 'GB',
    UnitedStatesOutlyingIslands = 'UM',
    Uruguay = 'UY',
    Uzbekistan = 'UZ',
    Vanuatu = 'VU',
    Venezuela = 'VE',
    VietNam = 'VN',
    VirginIslandsBritish = 'VG',
    VirginIslandsUS = 'VI',
    WallisAndFutuna = 'WF',
    WesternSahara = 'EH',
    Yemen = 'YE',
    Zambia = 'ZM',
    Zimbabwe = 'ZW',
    Unknown = 'UN'
}

export enum CountryPhoneCodes {
    AC = 247,
    AD = 376,
    AE = 971,
    AF = 93,
    AG = 1,
    AI = 1,
    AL = 355,
    AM = 374,
    AO = 244,
    AR = 54,
    AS = 1,
    AT = 43,
    AU = 61,
    AW = 297,
    AX = 358,
    AZ = 994,
    BA = 387,
    BB = 1,
    BD = 880,
    BE = 32,
    BF = 226,
    BG = 359,
    BH = 973,
    BI = 257,
    BJ = 229,
    BL = 590,
    BM = 1,
    BN = 673,
    BO = 591,
    BQ = 599,
    BR = 55,
    BS = 1,
    BT = 975,
    BW = 267,
    BY = 375,
    BZ = 501,
    CA = 1,
    CC = 61,
    CD = 243,
    CF = 236,
    CG = 242,
    CH = 41,
    CI = 225,
    CK = 682,
    CL = 56,
    CM = 237,
    CN = 86,
    CO = 57,
    CR = 506,
    CU = 53,
    CV = 238,
    CW = 599,
    CX = 61,
    CY = 357,
    CZ = 420,
    DE = 49,
    DJ = 253,
    DK = 45,
    DM = 1,
    DO = 1,
    DZ = 213,
    EC = 593,
    EE = 372,
    EG = 20,
    EH = 212,
    ER = 291,
    ES = 34,
    ET = 251,
    FI = 358,
    FJ = 679,
    FK = 500,
    FM = 691,
    FO = 298,
    FR = 33,
    GA = 241,
    GB = 44,
    GD = 1,
    GE = 995,
    GF = 594,
    GG = 44,
    GH = 233,
    GI = 350,
    GL = 299,
    GM = 220,
    GN = 224,
    GP = 590,
    GQ = 240,
    GR = 30,
    GT = 502,
    GU = 1,
    GW = 245,
    GY = 592,
    HK = 852,
    HN = 504,
    HR = 385,
    HT = 509,
    HU = 36,
    ID = 62,
    IE = 353,
    IL = 972,
    IM = 44,
    IN = 91,
    IO = 246,
    IQ = 964,
    IR = 98,
    IS = 354,
    IT = 39,
    JE = 44,
    JM = 1,
    JO = 962,
    JP = 81,
    KE = 254,
    KG = 996,
    KH = 855,
    KI = 686,
    KM = 269,
    KN = 1,
    KP = 850,
    KR = 82,
    KW = 965,
    KY = 1,
    KZ = 7,
    LA = 856,
    LB = 961,
    LC = 1,
    LI = 423,
    LK = 94,
    LR = 231,
    LS = 266,
    LT = 370,
    LU = 352,
    LV = 371,
    LY = 218,
    MA = 212,
    MC = 377,
    MD = 373,
    ME = 382,
    MF = 590,
    MG = 261,
    MH = 692,
    MK = 389,
    ML = 223,
    MM = 95,
    MN = 976,
    MO = 853,
    MP = 1,
    MQ = 596,
    MR = 222,
    MS = 1,
    MT = 356,
    MU = 230,
    MV = 960,
    MW = 265,
    MX = 52,
    MY = 60,
    MZ = 258,
    NA = 264,
    NC = 687,
    NE = 227,
    NF = 672,
    NG = 234,
    NI = 505,
    NL = 31,
    NO = 47,
    NP = 977,
    NR = 674,
    NU = 683,
    NZ = 64,
    OM = 968,
    PA = 507,
    PE = 51,
    PF = 689,
    PG = 675,
    PH = 63,
    PK = 92,
    PL = 48,
    PM = 508,
    PR = 1,
    PS = 970,
    PT = 351,
    PW = 680,
    PY = 595,
    QA = 974,
    RE = 262,
    RO = 40,
    RS = 381,
    RU = 7,
    RW = 250,
    SA = 966,
    SB = 677,
    SC = 248,
    SD = 249,
    SE = 46,
    SG = 65,
    SH = 290,
    SI = 386,
    SJ = 47,
    SK = 421,
    SL = 232,
    SM = 378,
    SN = 221,
    SO = 252,
    SR = 597,
    SS = 211,
    ST = 239,
    SV = 503,
    SX = 1,
    SY = 963,
    SZ = 268,
    TA = 290,
    TC = 1,
    TD = 235,
    TG = 228,
    TH = 66,
    TJ = 992,
    TK = 690,
    TL = 670,
    TM = 993,
    TN = 216,
    TO = 676,
    TR = 90,
    TT = 1,
    TV = 688,
    TW = 886,
    TZ = 255,
    UA = 380,
    UG = 256,
    US = 1,
    UY = 598,
    UZ = 998,
    VA = 39,
    VC = 1,
    VE = 58,
    VG = 1,
    VI = 1,
    VN = 84,
    VU = 678,
    WF = 681,
    WS = 685,
    XK = 383,
    YE = 967,
    YT = 262,
    ZA = 27,
    ZM = 260,
    ZW = 263
}

export enum DurationFormat {
    MilliSeconds,
    Seconds,
    Minutes,
    Hours,
    Days,
    Weeks,
    Months,
    Years,
    Auto,
    Default,  
    Integer,
    Number
}

export enum EmailType {
    Personal,
    Work,
    Other,
    Unknown
}

export enum Gender {
    Male = 'male',
    Female = 'female',
    Transgender = 'other',
    Unknown = 'Unknown'
}

export enum Language {
    Braille = 'braille',
    Chinese = 'chinese',
    Deutsch = 'deutsch',
    English = 'english',
    French = 'french',
    Hindi = 'hindi',
    Other = 'other',
    Russian = 'rusian',
    Sign = 'sign',
    Spanish = 'spanish',
    Tamil = 'tamil',
    Telugu = 'telugu',
    Unknown = 'Unknown',
    Urdu = 'urdu',
}

export enum PersonRelationType {
    Aunt,
    Brother,    
    CareTaker,
    Child,
    Cousign,
    Father,
    Friend,
    GrandFather,
    GrandMother,
    GrancChild,
    Guardian,
    Husband,
    Mother,
    Other,  
    Spouse,
    Sister,
    Uncle,
    Unknown,
    Wife
}

export enum PhoneType {
    Mobile,
    Home,
    Work,
    Fax,
    Other,
    Unknown
}

export enum Program {
    CCM,
    RPM
}

export enum StatesOfUSA {
    Alabama = 'AL',
    Alaska = 'AK',
    Arizona = 'AZ',
    Arkansas = 'AR',
    California = 'CA',
    Colorado = 'CO',
    Connecticut = 'CT',
    Delaware = 'DE',
    Florida = 'FL',
    Georgia = 'GA',
    Hawaii = 'HI',
    Idaho = 'ID',
    Illinois = 'IL',
    Indiana = 'IN',
    Iowa = 'IA',
    Kansas = 'KS',
    Kentucky = 'KY',
    Louisiana = 'LA',
    Maine = 'ME',
    Maryland = 'MD',
    Massachusetts = 'MA',
    Michigan = 'MI',
    Minnesota = 'MN',
    Mississippi = 'MS',
    Missouri = 'MO',
    Montana = 'MT',
    Nebraska = 'NE',
    Nevada = 'NV',
    NewHampshire = 'NH',
    NewJersey = 'NJ',
    NewMexico = 'NM',
    NewYork = 'NY',
    NorthCarolina = 'NC',
    NorthDakota = 'ND',
    Ohio = 'OH',
    Oklahoma = 'OK',
    Oregon = 'OR',
    Pennsylvania = 'PA',
    RhodeIsland = 'RI',
    SouthCarolina = 'SC',
    SouthDakota = 'SD',
    Tennessee = 'TN',
    Texas = 'TX',
    Utah = 'UT',
    Vermont = 'VT',
    Virginia = 'VI',
    Washington = 'WA',
    WestVirginia = 'WV',
    Wisconsin = 'WI',
    Wyoming = 'WY'
}

export enum WeekDays {
    Monday,
    Tuesday,
    Wednesday,
    Thursday,
    Friday,
    Saturday,
    Sunday,
    All,
    Any
}